languageCode = "en-us"
title = "David Martin"
baseurl = "http://www.daviddoesathing.com/"
theme = "prologue"
googleAnalytics = "UA-100790037-1"

[params]
  name = "David Martin"
  description = "Helping Friendly Developer"
  copyright = "Untitled."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "http://twitter.com/DaveMartin_"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://github.com/thenorthstarblues"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "http://linkedin.com/in/davidjamesmartin1"

  [[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "http://instagram.com/thenorthstarblues"

# Portfolio column one

[[params.portfolio1]]
  title = "Mallets"
  alt = ""
  source = "img/pic02.jpg"
  url = "https://www.playmallets.com"

# Portfolio column two

[[params.portfolio2]]
  title = "Hops of Grace"
  alt = ""
  source = "img/pic04.jpg"
  url = "http://github.com/ayoung09/Hops-of-Grace"

# Portfolio column 3

[[params.portfolio3]]
  title = "Agile Armature"
  alt = ""
  source = "img/pic06.jpg"
  url = "http://github.com/thenorthstarblues/agile-armature"
